### ISSUE TITLE
getRowStyle() with undefined data

### ISSUE THREAD

**Issue by rsmything** [ceolter/ag-grid-enterprise#54]
![image](https://cloud.githubusercontent.com/assets/11719983/17683152/036c8208-636a-11e6-89ef-702130fd71bd.png)

if I quickly scroll down, the new rows which were downloaded Ajax do not get the "object" as the parameter of function getRowStyle(params).

if I scroll up the page and down again, it will draw the rows is already normal.

**Comment by rsmything** [comment]
The problem with the first rows of "new next page" in virtual mode. Their surprising number still displayed the width of the table, all of the following row drawn normal.
![image](https://cloud.githubusercontent.com/assets/11719983/17683460/69cb3394-636c-11e6-82f2-2ed5c7f9d414.png)

**Comment by ceolter** [comment]
fixed. will be in next release.

Callbacks getRowStyle and getRowClass get called after the data is set as well as when the row is created.

**Comment by elhay-av** [comment]
Callbacks getRowStyle and getRowClass **still not** called after the data is set.

version: 11.0.0
with ag-grid-react@11.0.0

**Comment by elhay-av** [comment]
temporary solution is to trigger `refreshView` after `successCallback` on first time

```
const getRows = () => {
  params.successCallback(...);
  gridApi.refreshView();
}
```

**Comment by jayrungta** [comment]
This really needs to be fixed. When rowModelType is infinity, most of the functions don't have any params.data.
